sudo: required

language:
  - python

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends --no-install-suggests -y build-essential libreadline-dev libffi-dev pkg-config
  - sudo pip install pycodestyle
  # clone micropython, belyalov's fork of micropython-lib
  - git clone --recurse-submodules https://github.com/micropython/micropython.git
  - git clone https://github.com/belyalov/micropython-lib.git
  # merge required uasyncio modules
  - cp micropython-lib/uasyncio.core/uasyncio/core.py micropython-lib/uasyncio/uasyncio/core.py
  # make symlinks to required modules
  - export MDST=~/.micropython/lib/
  - mkdir -p $MDST
  - ln -s `pwd`/micropython-lib/unittest/unittest.py $MDST
  - ln -s `pwd`/micropython-lib/logging/logging.py $MDST
  - ln -s `pwd`/micropython-lib/uasyncio/uasyncio $MDST/uasyncio
  - ln -s `pwd`/tinyweb $MDST/tinyweb
  # compile/install micropython.
  - cd micropython
  - git checkout v1.11
  - sudo make -C ports/unix axtls install
  - cd ..

script:
  # Run style checks
  - pycodestyle --ignore=E501,W504 tinyweb/ test/
  # Run unittests
  - ./test/test_server.py
  # Copy modules to be frozen and compile firmware for esp8266
  - export MPORT=micropython/ports/esp8266/modules
  - cp -r tinyweb $MPORT
  - cp -r micropython-lib/uasyncio/uasyncio $MPORT
  - cp micropython-lib/logging/logging.py $MPORT
  # Copy examples - to freeze them as well
  - mkdir -p $MPORT/examples
  - cp examples/*.py $MPORT/examples
  # Compile firmware for esp8266
  - docker run -v`pwd`/micropython:/micropython arsenicus/esp-open-sdk /bin/bash -c ". /.bashrc && cd /micropython/ports/esp8266 && make"
  - cp micropython/ports/esp8266/build/firmware-combined.bin ./firmware_esp8266-$TRAVIS_TAG.bin
  # Compile firmware for esp32
  - export MPORT=micropython/ports/esp32/modules
  - cp -r tinyweb $MPORT
  - cp -r micropython-lib/uasyncio/uasyncio $MPORT
  - cp micropython-lib/logging/logging.py $MPORT
  # Copy examples - to freeze them as well
  - mkdir -p $MPORT/examples
  - cp examples/*.py $MPORT/examples
  # Supported ESP32 SDK
  - docker run -v`pwd`/micropython:/micropython arsenicus/esp32-open-sdk:30545f4cccec7460634b656d278782dd7151098e /bin/bash -c ". /.bashrc && cd /micropython/ports/esp32 && make"
  - cp micropython/ports/esp32/build/firmware.bin ./firmware_esp32-$TRAVIS_TAG.bin

deploy:
  provider: releases
  api_key:
    secure: LN9yw25ZRZt+xnD7+0Dy+kJ0EPk5AnrBfvtCsPrCRsRvb8NK+vrNtxxnslim49XpFTDOG712cDAfLnoz+SRZM1ZZn4IPmAsEFmU7FoFNTXWFt44xW6L17ER4bsGFCzLoWDohk7+Ps8V4ZOnbNXa0jm2i8FA8WuLzTBjn/btJSGxnfJei2fTYYenz96/LyaO7c1p7iaq12hcvcd15NQKSOF+JTgJV1NiPSzI8bg7HgqGR/o00Rdm5Gr91iuI97hCCVXhqfFx/VXkvOo5RwR9Ka0nNSzNg4Ijmxwv04uEHJ2pRnCOGqC951ksKu8D6+D2nHMYpNSUKwwkBy+1d3oRwN376oE46sXjX29xzxDf7Iun4F8WPh8bqhS0qfZNM3luHvjFQeXmxPCL633NkaR4P8dhWoZGxP7DECzG7bVEDvraZK1pXyFN/Ihn05AYWwZQxbbdD0t6Y6d5skguN2rGkGK5tZlzMIqrxxaZji5XDupWfJtOYQmcHRWcEsEb2Rhe5692n2AsIeSNHvBfU+rMpZyGSdiawphVo468ANzxoYVyCBcc9ymMORBOmb3Fb8bbMcCQNFs2hjwAZkxV1PyjN9GRyh7CoHoS1xLA2eryO/2UWkih1RSQbV6Ovk/XEW9ahQEBcRCXylAT2fanxdPfpqYadRk/8yToKNBbuDoGjILA=
  file:
    - firmware_esp8266-$TRAVIS_TAG.bin
    - firmware_esp32-$TRAVIS_TAG.bin
  skip_cleanup: true
  on:
    tags: true
